SELECT * FROM
(WITH CAL AS 
( SELECT A.PREVIOUSWORKDAY
 FROM DWH.D_CALENDAR A
 WHERE A.CALENDAR_DATE=TRUNC(SYSDATE)
)
SELECT TO_DATE(TO_CHAR(CREATED_DATE_TIME,'DD-Mon-YYYY')) AS KREDITIN_VERILME_TARIXI,
       VOEN,
       COUNT(CIF) AS SAY,
       CASE
         WHEN COUNT(CIF) > 3 THEN 'RED FLAG'
         ELSE
          'OKAY'
       END CHECKING
  FROM OPTIMUS.D_CONTRACT
 WHERE TO_DATE(TO_CHAR(CREATED_DATE_TIME,'DD-Mon-YYYY')) = (SELECT PREVIOUSWORKDAY FROM CAL)
       AND VOEN IS NOT NULL
 GROUP BY VOEN,
          TO_DATE(TO_CHAR(CREATED_DATE_TIME,'DD-Mon-YYYY'))
 ORDER BY SAY DESC) K
 WHERE K.CHECKING = 'RED FLAG'
