SELECT distinct C1.CONTRACT_REF_NO,
       GL.COLLATERAL_REF_NO,
       C1.CIF,
       C1.CMS_ID,
       C1.CUSTOMER_NAME,
       D.PIN,
       D.REGISTERED_ADDRESS_CITY  AS QEYDIYYAT_SHEHERI,
       D.REGISTERED_ADDRESS       AS QEYDIYYAT_UNVANI,
       D.REGISTRATION_DATE        AS QEYDIYYAT_ZAMANI,
       D.RESIDENTIAL_ADDRESS_CITY AS YASHAYISH_SHEHERI,
       D.RESIDENTIAL_ADDRESS      AS YASHAYISH_UNVANI,
       G.PROPRETY_ADDRESS         AS IPOEKAYA_ELDE_OLUNAN_EMLAK,
       D.TELEPHONE,
       D.EMPLOYER,
       D.INCOME_KIND,
       C1.START_DATE,
       C1.MATURITY_DATE,
       C1.INITIAL_AMOUNT,
       C1.CURRENT_ACCOUNT,
       C1.SALARY_CARD_ACCOUNT,
       C1.CREDIT_CARD_ACCOUNT,
       C1.EXPERT_HR_CODE,
       C1.EXPERT_NAME,
       B.BRANCH_NAME
  FROM DWH.D_CONTRACT_CREDIT C1
  JOIN DWH.D_CUSTOMER D
    ON D.CIF = C1.CIF
  JOIN DWH.D_BRANCH B
    ON C1.BRANCH_CODE = B.BRANCH_CODE
  JOIN DWH.D_CONTRACT_GUARANTEE_LINK GL
    ON GL.CONTRACT_REF_NO = C1.CONTRACT_REF_NO
  JOIN DWH.D_CONTRACT_GUARANTEE G
    ON GL.COLLATERAL_REF_NO = G.COLLATERAL_REF_NO
 WHERE CONTRACT_STATUS = 0
       AND (LOWER(C1.PRODUCT_CODE) LIKE '%ip%' OR
       LOWER(C1.PRODUCT_CODE) LIKE '%m_da%')
       AND C1.BRANCH_CODE IN ('191',
                              '193',
                              '196',
                              '199',
                              '200',
                              '156',
                              '102',
                              '104',
                              '105',
                              '106',
                              '172',
                              '217',
                              '218',
                              '226',
                              '298',
                              '234',
                              '241',
                              '115',
                              '117',
                              '118',
                              '119',
                              '120',
                              '121',
                              '122',
                              '123',
                              '125',
                              '126',
                              '198',
                              '108',
                              '109',
                              '110',
                              '111',
                              '113',
                              '114',
                              '112',
                              '116',
                              '195',
                              '103',
                              '107',
                              '194',
                              '207',
                              '142',
                              '190',
                              '204',
                              '000',
                              '201',
                              '202',
                              '203',
                              '208',
                              '214',
                              '213',
                              '210',
                              '211',
                              '220',
                              '221',
                              '228',
                              '229',
                              '231',
                              '232',
                              '233',
                              '235',
                              '237',
                              '238',
                              '239',
                              '240',
                              '242') and C1.START_DATE between '01-Jan-2022' and '31-Oct-2022' 
