WITH CREDIT AS
(SELECT D.CIF,
         D.CMS_ID,
         D.CUSTOMER_NAME,
         D.CREATE_DATE,
         D.FOND_CUSTOMER_NO
    FROM DWH.D_CONTRACT_CREDIT D),
TRANZAKSIYA AS
(SELECT T.BANK_DATE,
         T.ACCOUNTNOONE,
         T.LCY_AMOUNT,
         SUBSTR(T.USERDATA,
                INSTR(T.USERDATA,'/',1) + 1,LENGTH(SUBSTR(T.USERDATA,INSTR(T.USERDATA,'/',1) + 1)) - 1) AS USERDATA_NUMBER
    FROM CMS.F_TRANSACTION_DETAILS T
   WHERE T.TERMCODE = 65108),
KART AS
(SELECT C.CIF,
         C.CMS_ID,
         C.NAME,
         C.ACCOUNT
    FROM CMS.D_CARD C
    WHERE C.STATUS = '1')
SELECT DISTINCT D.CIF AS MUSHTERI_CIF,
       D.CMS_ID AS MUSHTERI_CMS_ID,
       D.CUSTOMER_NAME AS MUSHTERI_ADI,
       D.CREATE_DATE AS KREDITIN_VERILME_TARIXI,
       A.BANK_DATE AS TRANZAKSIYA_TARIXI,
       A.ACCOUNTNOONE AS MUSHTERI_HESABI,
       A.LCY_AMOUNT AS MEBLEG,
       K.CIF AS ODEYEN_MUSHERININ_CIFI,
       K.CMS_ID AS ODEYEN_MUSHTERININ_CMS_ID,
       K.NAME AS ODEYEN_MUSHTERININ_ADI,
       CASE WHEN D.CIF = K.CIF OR D.CMS_ID = K.CMS_ID THEN 'ACCEPTABLE'
         ELSE 'NOT ACCEPTABLE'
           END CHECKING
  FROM TRANZAKSIYA A
  JOIN CREDIT D
    ON D.FOND_CUSTOMER_NO = A.USERDATA_NUMBER
  JOIN KART K
    ON K.ACCOUNT = A.ACCOUNTNOONE
WHERE A.BANK_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-08-31'
